version: "3"

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
      - "9004:9004"
    environment:
      JAVA_OPTS: "-Xms1g -Xmx1g
                  -Dcom.sun.management.jmxremote
                  -Dcom.sun.management.jmxremote.port=9004
                  -Dcom.sun.management.jmxremote.rmi.port=9004
                  -Dcom.sun.management.jmxremote.ssl=false
                  -Dcom.sun.management.jmxremote.authenticate=true
                  -Djava.rmi.server.hostname=localhost
                  -Dcom.sun.management.jmxremote.password.file=/usr/local/tomcat/conf/jmxremote.password
                  -Dcom.sun.management.jmxremote.access.file=/usr/local/tomcat/conf/jmxremote.access
                  -Djava.security.manager
                  -Djava.security.policy=/usr/local/tomcat/conf/app.policy"
    volumes:
      - ./config/tomcat/jmxremote.access:/usr/local/tomcat/conf/jmxremote.access
      - ./config/tomcat/jmxremote.password:/usr/local/tomcat/conf/jmxremote.password
      - ./config/tomcat/jmxremote.policy:/usr/local/tomcat/conf/jmxremote.policy

    entrypoint: 'bash -c "cat /usr/local/tomcat/conf/jmxremote.policy /usr/local/tomcat/conf/catalina.policy > /usr/local/tomcat/conf/app.policy && catalina.sh run"'

  # jconsole:
  #   image: openjdk:8
  #   container_name: jconsole
  #   entrypoint: ["/bin/bash", "-c", "/usr/local/openjdk-8/bin/jconsole"]
